Contazul/Contazul-war/src/java/blue/PygController.java
package blue;

import blue.util.JsfUtil;
import blue.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "pygController")
@SessionScoped
public class PygController implements Serializable {

    private Pyg current;
    private DataModel items = null;
    @EJB
    private blue.PygFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PygController() {
    }

    public Pyg getSelected() {
        if (current == null) {
            current = new Pyg();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PygFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Pyg) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Pyg();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PygCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Pyg) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PygUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Pyg) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PygDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Pyg.class)
    public static class PygControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PygController controller = (PygController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "pygController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Pyg) {
                Pyg o = (Pyg) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Pyg.class.getName());
            }
        }

    }

}

Contazul/Contazul-war/web/pyg/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatePygTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePygLabel_id}" for="id" />
                    <h:inputText id="id" value="#{pygController.selected.id}" title="#{bundle.CreatePygTitle_id}" required="true" requiredMessage="#{bundle.CreatePygRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreatePygLabel_usuariosidUsuarios}" for="usuariosidUsuarios" />
                    <h:selectOneMenu id="usuariosidUsuarios" value="#{pygController.selected.usuariosidUsuarios}" title="#{bundle.CreatePygTitle_usuariosidUsuarios}" required="true" requiredMessage="#{bundle.CreatePygRequiredMessage_usuariosidUsuarios}">
                        <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreatePygLabel_companiesidCompanies}" for="companiesidCompanies" />
                    <h:selectOneMenu id="companiesidCompanies" value="#{pygController.selected.companiesidCompanies}" title="#{bundle.CreatePygTitle_companiesidCompanies}" required="true" requiredMessage="#{bundle.CreatePygRequiredMessage_companiesidCompanies}">
                        <f:selectItems value="#{companiesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pygController.create}" value="#{bundle.CreatePygSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{pygController.prepareList}" value="#{bundle.CreatePygShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreatePygIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Contazul/Contazul-war/web/pyg/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPygTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPygLabel_id}" for="id" />
                    <h:inputText id="id" value="#{pygController.selected.id}" title="#{bundle.EditPygTitle_id}" required="true" requiredMessage="#{bundle.EditPygRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditPygLabel_usuariosidUsuarios}" for="usuariosidUsuarios" />
                    <h:selectOneMenu id="usuariosidUsuarios" value="#{pygController.selected.usuariosidUsuarios}" title="#{bundle.EditPygTitle_usuariosidUsuarios}" required="true" requiredMessage="#{bundle.EditPygRequiredMessage_usuariosidUsuarios}">
                        <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditPygLabel_companiesidCompanies}" for="companiesidCompanies" />
                    <h:selectOneMenu id="companiesidCompanies" value="#{pygController.selected.companiesidCompanies}" title="#{bundle.EditPygTitle_companiesidCompanies}" required="true" requiredMessage="#{bundle.EditPygRequiredMessage_companiesidCompanies}">
                        <f:selectItems value="#{companiesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{pygController.update}" value="#{bundle.EditPygSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditPygViewLink}"/>
                <br />
                <h:commandLink action="#{pygController.prepareList}" value="#{bundle.EditPygShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditPygIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Contazul/Contazul-war/web/pyg/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListPygTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPygEmpty}" rendered="#{pygController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{pygController.items.rowCount > 0}">
                    <h:outputText value="#{pygController.pagination.pageFirstItem + 1}..#{pygController.pagination.pageLastItem + 1}/#{pygController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{pygController.previous}" value="#{bundle.Previous} #{pygController.pagination.pageSize}" rendered="#{pygController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{pygController.next}" value="#{bundle.Next} #{pygController.pagination.pageSize}" rendered="#{pygController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{pygController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPygTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPygTitle_usuariosidUsuarios}"/>
                            </f:facet>
                            <h:outputText value="#{item.usuariosidUsuarios}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPygTitle_companiesidCompanies}"/>
                            </f:facet>
                            <h:outputText value="#{item.companiesidCompanies}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{pygController.prepareView}" value="#{bundle.ListPygViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pygController.prepareEdit}" value="#{bundle.ListPygEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pygController.destroy}" value="#{bundle.ListPygDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{pygController.prepareCreate}" value="#{bundle.ListPygCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListPygIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

Contazul/Contazul-war/web/pyg/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewPygTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewPygLabel_id}"/>
                    <h:outputText value="#{pygController.selected.id}" title="#{bundle.ViewPygTitle_id}"/>
                    <h:outputText value="#{bundle.ViewPygLabel_usuariosidUsuarios}"/>
                    <h:outputText value="#{pygController.selected.usuariosidUsuarios}" title="#{bundle.ViewPygTitle_usuariosidUsuarios}"/>
                    <h:outputText value="#{bundle.ViewPygLabel_companiesidCompanies}"/>
                    <h:outputText value="#{pygController.selected.companiesidCompanies}" title="#{bundle.ViewPygTitle_companiesidCompanies}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pygController.destroyAndView}" value="#{bundle.ViewPygDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewPygEditLink}"/>
                <br />
                <h:commandLink action="#{pygController.prepareCreate}" value="#{bundle.ViewPygCreateLink}" />
                <br />
                <h:commandLink action="#{pygController.prepareList}" value="#{bundle.ViewPygShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewPygIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>